#!/bin/bash

modsPath='./mods'
if [ -d $modsPath ]; then
	rm -r $modsPath
fi
mkdir mods

fn() {
	local="../$1"
	if [ ! -d "$local" ]; then
		remote="https://github.com/RPG-Paper-Maker/$1"
		echo "clone Github repository: $remote -> $local"
		git clone "$remote" "$local"
	fi
	echo "Local copy: $local/$2 -> $3"
	cp -r "$local/$2" "$3"
}

fn 'Game-Scripts-Build' 'Scripts' "${modsPath}/Scripts"
fn 'Game-Scripts' 'main.js' "${modsPath}/main.js"
fn 'Game-Scripts' 'index.html' "${modsPath}/index.html"
fn 'Game-Scripts' 'package.json' "${modsPath}/package.json"
mkdir "${modsPath}/BR"
fn 'Basic-Ressources' 'Content' "${modsPath}/BR/Content"
fn 'Dependencies' 'Game' "${modsPath}/Game"
