/*
    RPG Paper Maker Copyright (C) 2017-2026 Wano

    RPG Paper Maker engine is under proprietary license.
    This source code is also copyrighted.

    Use Commercial edition for commercial use of your games.
    See RPG Paper Maker EULA here:
        http://rpg-paper-maker.com/index.php/eula.
*/

import { configureStore } from '@reduxjs/toolkit';
import {
	MapEditorReducer,
	setCurrentActionKind,
	setCurrentAutotileID,
	setCurrentAutotileTexture,
	setCurrentElementPositionKind,
	setCurrentLayerKind,
	setCurrentMapElementKind,
	setCurrentMountainHeightPixels,
	setCurrentMountainHeightSquares,
	setCurrentMountainID,
	setCurrentMountainAllSides,
	setCurrentMountainTopFloorIsAutotile,
	setCurrentMountainTopFloorTilesetRect,
	setCurrentMountainTopFloorAutotileID,
	setCurrentMountainTopFloorAutotileRect,
	setCurrentMountainWidthPixelsBot,
	setCurrentMountainWidthPixelsLeft,
	setCurrentMountainWidthPixelsRight,
	setCurrentMountainWidthPixelsTop,
	setCurrentMountainWidthSquaresBot,
	setCurrentMountainWidthSquaresLeft,
	setCurrentMountainWidthSquaresRight,
	setCurrentMountainWidthSquaresTop,
	setCurrentObject3DID,
	setCurrentTilesetFloorSpriteTexture,
	setCurrentTreeMapTag,
	setCurrentWallID,
	setMapEditorLoaded,
	setNeedsUpdateMapEditor,
	setSelectedMapElement,
	setSelectedPosition,
	setUndoRedoIndex,
	setUndoRedoLength,
} from './slices/MapEditorReducer';
import {
	clearProjects,
	ProjectsReducer,
	setCopiedItems,
	setCurrentProject,
	setDialogsOpen,
	setErrorDialog,
	setIsSystemsDialogOpen,
	setLoading,
	setLoadingBar,
	setOpenLoading,
	setProjectMenuIndex,
	setProjects,
	showWarning,
} from './slices/ProjectsReducer';
import { setTheme, SettingsReducer } from './slices/SettingsReducer';
import {
	setNeedsReloadMap,
	setNeedsReloadPageClearCache,
	setNeedsReloadPageUpdate,
	triggerAutotiles,
	triggerCollisions,
	triggerData,
	triggerDLCs,
	triggerFonts,
	triggerImportProject,
	triggerKeyboard,
	triggerLanguages,
	triggerMenu,
	triggerMountains,
	triggerNewProject,
	triggerObjects3D,
	triggerOpenDialogProject,
	triggerOpenProject,
	triggerOpenProjectFolder,
	triggerPictures,
	triggerPlay,
	triggerPlugins,
	triggerSave,
	triggerSaveAll,
	triggerShapes,
	triggerSongs,
	triggerSplitting,
	TriggersReducer,
	triggerSystems,
	triggerTreeMap,
	triggerVariables,
	triggerVideos,
	triggerWalls,
} from './slices/TriggersReducer';

const store = configureStore({
	reducer: {
		mapEditor: MapEditorReducer,
		projects: ProjectsReducer,
		triggers: TriggersReducer,
		settings: SettingsReducer,
	},
	middleware: (getDefaultMiddleware) =>
		getDefaultMiddleware({
			serializableCheck: false,
		}),
});

export {
	clearProjects,
	setCopiedItems,
	setCurrentActionKind,
	setCurrentAutotileID,
	setCurrentAutotileTexture,
	setCurrentElementPositionKind,
	setCurrentLayerKind,
	setCurrentMapElementKind,
	setCurrentMountainHeightPixels,
	setCurrentMountainHeightSquares,
	setCurrentMountainID,
	setCurrentMountainAllSides,
	setCurrentMountainTopFloorIsAutotile,
	setCurrentMountainTopFloorTilesetRect,
	setCurrentMountainTopFloorAutotileID,
	setCurrentMountainTopFloorAutotileRect,
	setCurrentMountainWidthPixelsBot,
	setCurrentMountainWidthPixelsLeft,
	setCurrentMountainWidthPixelsRight,
	setCurrentMountainWidthPixelsTop,
	setCurrentMountainWidthSquaresBot,
	setCurrentMountainWidthSquaresLeft,
	setCurrentMountainWidthSquaresRight,
	setCurrentMountainWidthSquaresTop,
	setCurrentObject3DID,
	setCurrentProject,
	setCurrentTilesetFloorSpriteTexture,
	setCurrentTreeMapTag,
	setCurrentWallID,
	setDialogsOpen,
	setErrorDialog,
	setIsSystemsDialogOpen,
	setLoading,
	setLoadingBar,
	setMapEditorLoaded,
	setNeedsReloadMap,
	setNeedsReloadPageClearCache,
	setNeedsReloadPageUpdate,
	setNeedsUpdateMapEditor,
	setOpenLoading,
	setProjectMenuIndex,
	setProjects,
	setSelectedMapElement,
	setSelectedPosition,
	setTheme,
	setUndoRedoIndex,
	setUndoRedoLength,
	showWarning,
	store,
	triggerAutotiles,
	triggerCollisions,
	triggerData,
	triggerDLCs,
	triggerFonts,
	triggerImportProject,
	triggerKeyboard,
	triggerLanguages,
	triggerMenu,
	triggerMountains,
	triggerNewProject,
	triggerObjects3D,
	triggerOpenDialogProject,
	triggerOpenProject,
	triggerOpenProjectFolder,
	triggerPictures,
	triggerPlay,
	triggerPlugins,
	triggerSave,
	triggerSaveAll,
	triggerShapes,
	triggerSongs,
	triggerSplitting,
	triggerSystems,
	triggerTreeMap,
	triggerVariables,
	triggerVideos,
	triggerWalls,
};
export type RootState = ReturnType<typeof store.getState>;
