/**
 * The static class containing all the files paths.
 *
 * @class Paths
 */
declare class Paths {
    static readonly ROOT_DIRECTORY_LOCAL = ".";
    static readonly FILES = "file:///";
    static readonly DATAS: string;
    static readonly TEST: string;
    static readonly FILE_MAPS: string;
    static readonly FILE_MAP_INFOS = "/infos.json";
    static readonly FILE_MAP_OBJECTS = "/objects.json";
    static readonly FILE_PICTURES: string;
    static readonly FILE_VIDEOS: string;
    static readonly FILE_FONTS: string;
    static readonly FILE_SONGS: string;
    static readonly FILE_SHAPES: string;
    static readonly FILE_COMMON_EVENTS: string;
    static readonly FILE_ITEMS: string;
    static readonly FILE_SKILLS: string;
    static readonly FILE_WEAPONS: string;
    static readonly FILE_ARMORS: string;
    static readonly FILE_HEROES: string;
    static readonly FILE_MONSTERS: string;
    static readonly FILE_TROOPS: string;
    static readonly FILE_BATTLE_SYSTEM: string;
    static readonly FILE_TITLE_SCREEN_GAME_OVER: string;
    static readonly FILE_KEYBOARD: string;
    static readonly FILE_SYSTEM: string;
    static readonly FILE_CLASSES: string;
    static readonly FILE_TILESETS: string;
    static readonly FILE_SPECIAL_ELEMENTS: string;
    static readonly FILE_VARIABLES: string;
    static readonly FILE_SETTINGS: string;
    static readonly FILE_DLCS: string;
    static readonly FILE_ANIMATIONS: string;
    static readonly FILE_STATUS: string;
    static readonly FILE_SCRIPTS: string;
    static readonly FILE_LANGS: string;
    static readonly FILE_PROTECT: string;
    static readonly FILE_TEST: string;
    static readonly FILE_PLUGIN_CODE = "code.js";
    static readonly FILE_PLUGIN_DETAILS = "details.json";
    static readonly PICTURES = "/Content/Images";
    static readonly VIDEOS = "/Content/Videos";
    static readonly FONTS = "/Content/Fonts";
    static readonly HUD: string;
    static readonly TEXTURES2D: string;
    static readonly BARS: string;
    static readonly FACESETS: string;
    static readonly ICONS: string;
    static readonly WINDOW_SKINS: string;
    static readonly TITLE_SCREEN: string;
    static readonly GAME_OVER: string;
    static readonly HUD_PICTURES: string;
    static readonly ANIMATIONS: string;
    static readonly AUTOTILES: string;
    static readonly CHARACTERS: string;
    static readonly TILESETS: string;
    static readonly WALLS: string;
    static readonly BATTLERS: string;
    static readonly OBJECTS_3D: string;
    static readonly MOUNTAINS: string;
    static readonly SKYBOXES: string;
    static readonly PARTICLES: string;
    static readonly SONGS = "/Content/Songs/";
    static readonly MUSICS: string;
    static readonly BACKGROUND_SOUNDS: string;
    static readonly SOUNDS: string;
    static readonly MUSIC_EFFECTS: string;
    static readonly SHAPES = "/Content/Shapes/";
    static readonly OBJ: string;
    static readonly MTL: string;
    static readonly OBJ_COLLISIONS: string;
    static readonly SCRIPTS: string;
    static readonly PLUGINS: string;
    static readonly SYSTEM: string;
    static readonly SHADERS: string;
    static readonly SAVES: string;
    constructor();
}
export { Paths };
